# Generated by Django 5.0 on 2025-12-21 16:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner', models.CharField(choices=[('system', 'System'), ('user', 'User')], default='system', max_length=20)),
                ('auido_url', models.URLField(max_length=255)),
                ('duration', models.DurationField(help_text='Duration in seconds')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
