# Generated by Django 5.0 on 2025-12-18 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_post_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image_url',
            new_name='image',
        ),
    ]
