# Generated by Django 5.0 on 2025-12-20 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_image_url_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='poststats',
            name='post',
        ),
        migrations.DeleteModel(
            name='Audio',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='PostStats',
        ),
    ]
