# Generated by Django 5.0 on 2025-12-21 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_is_premium_alter_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auth_status',
            field=models.CharField(choices=[('new', 'new'), ('code_verified', 'code_verified'), ('done', 'done'), ('photo_step', 'photo_step')], default='new', max_length=31),
        ),
        migrations.AlterField(
            model_name='user',
            name='auth_type_choices',
            field=models.CharField(choices=[('via_phone', 'via_phone'), ('via_email', 'via_email')], default='via_phone', max_length=31),
        ),
    ]
