# Generated by Django 5.0 on 2025-12-25 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_auth_status_alter_user_auth_type_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='external_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
